# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5431/lab
spring.datasource.username=emc
spring.datasource.password=emc

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true